import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Principal from "./layout/Principal";
import "./globals.css";
import Selector from "./components/Selector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Principal />
        <div className="bg-sky-200 mx-auto p-1">
          <Selector />
        </div>
        <div className="mx-auto">
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
